# Generated by Django 5.2.1 on 2025-05-28 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('department', models.CharField(choices=[('engineering', 'Engineering & Development'), ('ai_ml', 'AI & Machine Learning'), ('hardware', 'Hardware & Robotics'), ('product', 'Product Management'), ('sales', 'Sales & Marketing'), ('operations', 'Operations'), ('finance', 'Finance & Administration'), ('hr', 'Human Resources')], max_length=20)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('internship', 'Internship'), ('contract', 'Contract'), ('remote', 'Remote')], max_length=20)),
                ('experience_level', models.CharField(choices=[('entry', 'Entry Level'), ('junior', 'Junior (1-3 years)'), ('mid', 'Mid Level (3-5 years)'), ('senior', 'Senior (5+ years)'), ('lead', 'Lead/Principal')], max_length=20)),
                ('location', models.CharField(default='Bangalore, India', max_length=100)),
                ('remote_allowed', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('responsibilities', models.TextField()),
                ('requirements', models.TextField()),
                ('nice_to_have', models.TextField(blank=True)),
                ('benefits', models.TextField(blank=True)),
                ('salary_min', models.IntegerField(blank=True, help_text='Minimum salary in INR per annum', null=True)),
                ('salary_max', models.IntegerField(blank=True, help_text='Maximum salary in INR per annum', null=True)),
                ('equity_offered', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('applications_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('current_location', models.CharField(max_length=100)),
                ('willing_to_relocate', models.BooleanField(default=False)),
                ('current_company', models.CharField(blank=True, max_length=100)),
                ('current_role', models.CharField(blank=True, max_length=100)),
                ('years_experience', models.CharField(choices=[('0', 'Fresh Graduate'), ('1', '1 Year'), ('2', '2 Years'), ('3', '3 Years'), ('4', '4 Years'), ('5', '5 Years'), ('6-10', '6-10 Years'), ('10+', '10+ Years')], max_length=20)),
                ('resume', models.FileField(help_text='Upload your resume (PDF format preferred)', upload_to='resumes/')),
                ('cover_letter', models.TextField(help_text='Tell us why you want to join SegriTech')),
                ('portfolio_url', models.URLField(blank=True, help_text='Link to your portfolio/GitHub/LinkedIn')),
                ('expected_salary', models.IntegerField(blank=True, help_text='Expected salary in INR per annum', null=True)),
                ('earliest_start_date', models.DateField(help_text='When can you start?')),
                ('visa_sponsorship_required', models.BooleanField(default=False)),
                ('reference1_name', models.CharField(blank=True, max_length=100)),
                ('reference1_email', models.EmailField(blank=True, max_length=254)),
                ('reference1_phone', models.CharField(blank=True, max_length=20)),
                ('reference1_relation', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('submitted', 'Application Submitted'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('offer_extended', 'Offer Extended'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes for HR team')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='first.jobposting')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('job_posting', 'email')},
            },
        ),
    ]
