# Generated by Django 5.2.1 on 2025-06-02 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_jobposting_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('category_type', models.CharField(choices=[('size_graders', 'Size Graders'), ('quality_graders', 'Quality Graders'), ('weight_graders', 'Weight Graders'), ('cleaning_machines', 'Cleaning Machines'), ('packing_robots', 'Packing Robots')], max_length=20, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=200)),
                ('image', models.ImageField(help_text='Category banner image', upload_to='categories/')),
                ('icon', models.CharField(default='fas fa-cogs', help_text='FontAwesome icon class', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(max_length=300)),
                ('detailed_description', models.TextField()),
                ('specifications', models.TextField(help_text='Technical specifications in JSON or structured format')),
                ('dimensions', models.CharField(blank=True, help_text='L x W x H', max_length=100)),
                ('weight', models.CharField(blank=True, max_length=50)),
                ('power_requirements', models.CharField(blank=True, max_length=100)),
                ('capacity', models.CharField(blank=True, help_text='Processing capacity per hour', max_length=100)),
                ('main_image', models.ImageField(upload_to='products/')),
                ('gallery_images', models.TextField(blank=True, help_text='Comma-separated list of image URLs')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo URL')),
                ('brochure', models.FileField(blank=True, upload_to='brochures/')),
                ('price_range', models.CharField(blank=True, help_text='e.g., ₹50,000 - ₹75,000', max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('lead_time', models.CharField(blank=True, help_text='Manufacturing/delivery time', max_length=50)),
                ('key_features', models.TextField(help_text='JSON list of key features')),
                ('applications', models.TextField(help_text='Suitable applications and use cases')),
                ('benefits', models.TextField(help_text='Key benefits and advantages')),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='first.productcategory')),
            ],
            options={
                'ordering': ['category', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('inquiry_type', models.CharField(choices=[('pricing', 'Pricing Information'), ('demo', 'Request Demo'), ('specs', 'Technical Specifications'), ('customization', 'Customization Options'), ('bulk_order', 'Bulk Order Inquiry'), ('partnership', 'Partnership Opportunity')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_responded', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='first.product')),
            ],
            options={
                'verbose_name': 'Product Inquiry',
                'verbose_name_plural': 'Product Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
