# Generated by Django 5.2.1 on 2025-06-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_productcategory_product_productinquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
    ]
