# Generated by Django 5.2.1 on 2025-06-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_alter_product_main_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('ai_tech', 'AI Technology'), ('sustainability', 'Sustainability'), ('market_access', 'Market Access'), ('automation', 'Automation'), ('research', 'Research'), ('case_study', 'Case Study'), ('industry_news', 'Industry News')], max_length=20)),
                ('author_name', models.CharField(max_length=100)),
                ('author_title', models.CharField(help_text='e.g., Research Scientist, Product Manager', max_length=100)),
                ('author_image', models.ImageField(blank=True, upload_to='blog_authors/')),
                ('excerpt', models.CharField(help_text='Short description shown on cards', max_length=300)),
                ('content', models.TextField(help_text='Full blog post content')),
                ('featured_image', models.ImageField(upload_to='blog_images/')),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=200)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('views_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('farmer', 'Farmer'), ('trader', 'Agricultural Trader'), ('cooperative_manager', 'Cooperative Manager'), ('extension_officer', 'Extension Officer'), ('ngo_director', 'NGO Director'), ('export_manager', 'Export Manager'), ('researcher', 'Research Scientist'), ('entrepreneur', 'Agricultural Entrepreneur'), ('consultant', 'Agricultural Consultant')], max_length=50)),
                ('company_or_location', models.CharField(help_text='Company name or location', max_length=150)),
                ('country', models.CharField(max_length=50)),
                ('quote', models.TextField(help_text='The testimonial quote')),
                ('impact_metric', models.CharField(help_text='e.g., 40% Loss Reduction, 500+ Farmers', max_length=100)),
                ('impact_icon', models.CharField(default='fas fa-chart-line', help_text='FontAwesome icon class', max_length=50)),
                ('photo', models.ImageField(upload_to='testimonials/')),
                ('video_url', models.URLField(blank=True, help_text='Optional video testimonial URL')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
