# Generated by Django 5.2.1 on 2025-06-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_blogpost_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaCoverageArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Article headline/title', max_length=200)),
                ('publication', models.CharField(help_text='Name of the publication', max_length=100)),
                ('category', models.CharField(choices=[('funding', 'Funding News'), ('founder_spotlight', 'Founder Spotlight'), ('demo_day', 'Demo Day'), ('accelerator', 'Accelerator'), ('awards', 'Awards & Recognition'), ('technology_impact', 'Technology Impact'), ('agritech_coverage', 'AgriTech Coverage'), ('industry_analysis', 'Industry Analysis'), ('partnership', 'Partnership'), ('product_launch', 'Product Launch'), ('research', 'Research & Development'), ('sustainability', 'Sustainability')], default='agritech_coverage', max_length=20)),
                ('icon', models.CharField(choices=[('fa-leaf', 'Leaf (Environment/Agriculture)'), ('fa-newspaper', 'Newspaper (General News)'), ('fa-chart-line', 'Chart Line (Growth/Analytics)'), ('fa-rocket', 'Rocket (Startups/Innovation)'), ('fa-industry', 'Industry (Technology)'), ('fa-seedling', 'Seedling (AgriTech)'), ('fa-globe', 'Globe (Global/International)'), ('fa-lightbulb', 'Lightbulb (Innovation)'), ('fa-trophy', 'Trophy (Awards)'), ('fa-medal', 'Medal (Achievement)'), ('fa-star', 'Star (Featured/Important)'), ('fa-award', 'Award (Recognition)'), ('fa-briefcase', 'Briefcase (Business)'), ('fa-handshake', 'Handshake (Partnership)'), ('fa-users', 'Users (Community)'), ('fa-cogs', 'Cogs (Technology)'), ('fa-bullhorn', 'Bullhorn (Announcement)'), ('fa-camera', 'Camera (Media)'), ('fa-microphone', 'Microphone (Interview)'), ('fa-tv', 'TV (Broadcast)'), ('fa-wifi', 'WiFi (Digital/Tech)'), ('fa-mobile', 'Mobile (Apps/Mobile)'), ('fa-laptop', 'Laptop (Software)'), ('fa-desktop', 'Desktop (Systems)')], default='fa-newspaper', help_text='FontAwesome icon to display with the article', max_length=20)),
                ('description', models.TextField(help_text='Brief description of the article (max 300 characters recommended)')),
                ('article_url', models.URLField(help_text='Direct link to the article')),
                ('featured_image', models.ImageField(blank=True, help_text='Optional image for the article card', upload_to='media_coverage/')),
                ('publication_date', models.DateField(help_text='Date when the article was published')),
                ('is_featured', models.BooleanField(default=False, help_text='Show prominently in media section')),
                ('external_publication', models.BooleanField(default=True, help_text='Is this from an external publication?')),
                ('is_active', models.BooleanField(default=True, help_text='Display this article in the slider')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which articles appear (lower numbers first)')),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('clicks_count', models.IntegerField(default=0, help_text='Number of times this article link was clicked')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Media Coverage Article',
                'verbose_name_plural': 'Media Coverage Articles',
                'ordering': ['display_order', '-publication_date'],
            },
        ),
    ]
