# Generated by Django 5.2.2 on 2025-06-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='external_url',
            field=models.URLField(blank=True, help_text='External URL (e.g., LinkedIn article link) - if provided, clicking will redirect to this URL'),
        ),
    ]
