# Generated by Django 5.2.2 on 2025-06-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0008_blogpost_external_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_sections',
            field=models.TextField(blank=True, help_text='JSON array for structured content sections - format: [{"type": "text|image|video|chart|quote", "content": "...", "style": "...", "order": 1}]'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='custom_css',
            field=models.TextField(blank=True, help_text='Custom CSS styles for this blog post only. Use <style> tags.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='custom_js',
            field=models.TextField(blank=True, help_text='Custom JavaScript for interactive elements. Use <script> tags.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='estimated_read_time',
            field=models.IntegerField(default=5, help_text='Estimated reading time in minutes'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='gallery_images',
            field=models.TextField(blank=True, help_text='JSON array of additional images for the blog post - format: [{"url": "/static/images/blog/image1.jpg", "caption": "Image caption", "alt": "Alt text"}]'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube/Vimeo URL for embedded video'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('automation', 'Automation'), ('research', 'Research'), ('case_study', 'Case Study'), ('industry_news', 'Industry News'), ('market-analysis', 'Market Analysis'), ('technology', 'Technology'), ('sustainability', 'Sustainability')], max_length=20),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(help_text='Full blog post content (supports HTML)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(help_text='Main image shown in cards and at top of article', upload_to='blog_images/'),
        ),
    ]
