# Generated by Django 5.2.1 on 2025-07-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0009_add_dynamic_blog_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='company_logo',
            field=models.ImageField(blank=True, help_text='Company logo to display with the job posting', null=True, upload_to='company_logos/'),
        ),
    ]
