# Generated by Django 5.2.2 on 2025-07-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0010_jobposting_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('is_featured', models.BooleanField(default=False, help_text='If selected, this question will appear on the homepage')),
                ('order', models.IntegerField(default=0, help_text='Order in which the question should appear')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='jobposting',
            options={'ordering': ['-created_at']},
        ),
        # Remove the RemoveField operation that's causing the issue
        # migrations.RemoveField(
        #     model_name='jobposting',
        #     name='is_featured',
        # ),
    ]
