# Generated by Django 5.2.2 on 2025-07-11 18:41

from django.db import migrations


def remove_is_featured_if_exists(apps, schema_editor):
    """Remove is_featured field from JobPosting if it exists"""
    db_alias = schema_editor.connection.alias
    JobPosting = apps.get_model('first', 'JobPosting')
    
    # Check if the field exists in the database
    try:
        # Try to access the field - if it doesn't exist, this will raise an exception
        JobPosting._meta.get_field('is_featured')
        # If we get here, the field exists, so we can safely remove it
        schema_editor.remove_field(JobPosting, JobPosting._meta.get_field('is_featured'))
    except:
        # Field doesn't exist, so we don't need to do anything
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0011_faq_alter_jobposting_options_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_is_featured_if_exists, reverse_code=migrations.RunPython.noop),
    ] 